language: ruby
rvm:
  - 2.0.0-p598
  - 2.1.5
  - 2.2.0
before_install:
  - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xf ImageMagick.tar.gz
  - cd ImageMagick*
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - compare -version
